### PR TITLE
Prevent wrapping unsupported version of CUDA functions.

### PR DESCRIPTION
**Pull request by Kerilk**
To discuss.

### CODE REVIEW

**Comment by TApplencourt** [comment]
LGTM!
No sure if we need to escape the `\` or `\n` or not

**Comment by TApplencourt** [comment]
The `\` doesn't show up
```
THAPI: CUDA version 12020 is unsupported, could not wrap cuMemPrefetchAsync symbol
```
So I guess we are good.

One of the problem, is that it may break the analysis (for example if don't wrap cuModuleLoad or whatever)

**Comment by bd4** [comment]
Is this for when the runtime lib version is newer than the version used at build time?

**Comment by TApplencourt** [comment]
Exactly! IE when we didn't update the header in THAPI

**Review by TApplencourt — APPROVED** [review]

**Pull request merged**
